### ------------------------------------------------------------
### github-style
### ------------------------------------------------------------
baseurl = "https://blog.kmgk.site/"
languageCode = "jp"
title = "kmgk's blog"
googleAnalytics = "G-74TC56JTJK"
theme = "github-style"

[params]
  author = "kmgk"
  description = "ãŠå¯¿å¸ã¯ãã“ãã“å¥½ãã§ã™"
  github = "kmgk"
  twitter = "kmgk21444557"
  url = "https://blog.kmgk.site"
  rss = true
  lastmod = true
  userStatusEmoji = "ðŸ£"
  favicon = "/images/maguro.png"
  avatar = "/images/maguro.png"
  location = "Japan"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

### ------------------------------------------------------------
### potato-dark
### ------------------------------------------------------------
# baseurl = "https://kmgk.dev"
# hasCJKLanguage = true
# languageCode = "jp"
# Title = "kmgk.dev"
# copyright = "&copy; kmgk 2020-"
# theme = "potato-dark"

# [params]
#   paginate = 10
#   # Social accounts. Link to these accounts are displayed in the header and
#   # footer
#   twitter = "kmgk21444557"
#   github = "kmgk"
#   # Disqus shortname
#   disqus = ""
#   # Google Analytics API key.
#   ga_api_key = "G-74TC56JTJK"
#   # Logo image. This is displayed ogp image.
#   logo = "/path/to/logo"
#   favicon = "/path/to/favicon"
#   author = "kmgk"
#   authorwebsite = "https://twitter.com/kmgk21444557"

# [[menu.main]]
#     name = "Blog"
#     url = "/"
#     weight = 1

# [[menu.main]]
#     name = "About"
#     url = "/about"
#     weight = 2

# [related]
#   # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
#   threshold = 80

#   # To get stable "See also" sections we, by default, exclude newer related pages.
#   includeNewer = false

#   # Will lower case keywords in both queries and in the indexes.
#   toLower = false

#   [[related.indices]]
#   name = "keywords"
#   weight = 150
#   [[related.indices]]
#   name  = "author"
#   toLower = true
#   weight = 30
#   [[related.indices]]
#   name  = "tags"
#   weight = 100
#   [[related.indices]]
#   name  = "date"
#   weight = 10
#   pattern = "2017"
